// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtBV1QgdI1X0dT7Kio1hvlB9N306FPWHM',
    appId: '1:582886206666:web:b45f3839ee92dfff085833',
    messagingSenderId: '582886206666',
    projectId: 'firstapp-bdde6',
    authDomain: 'firstapp-bdde6.firebaseapp.com',
    storageBucket: 'firstapp-bdde6.appspot.com',
    measurementId: 'G-PNN2S5JY9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANIDkw7-pZc-VbV3VGwDRFbqOI5Y3jxyI',
    appId: '1:582886206666:android:b92ab91719475428085833',
    messagingSenderId: '582886206666',
    projectId: 'firstapp-bdde6',
    storageBucket: 'firstapp-bdde6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKrTqx7sQ-iYvcAHJjQp1atS0xOsKwE48',
    appId: '1:582886206666:ios:fc4b468c3f2e6585085833',
    messagingSenderId: '582886206666',
    projectId: 'firstapp-bdde6',
    storageBucket: 'firstapp-bdde6.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKrTqx7sQ-iYvcAHJjQp1atS0xOsKwE48',
    appId: '1:582886206666:ios:89086ce492485d17085833',
    messagingSenderId: '582886206666',
    projectId: 'firstapp-bdde6',
    storageBucket: 'firstapp-bdde6.appspot.com',
    iosBundleId: 'com.example.firstapp.RunnerTests',
  );
}
